apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-frontend
  namespace: status-platform
  labels:
    app: status-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: status-frontend
  template:
    metadata:
      labels:
        app: status-frontend
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ecr-pull
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: 820932217554.dkr.ecr.eu-north-1.amazonaws.com/status-platform-dev-frontend:sha-e052359c9cfa5ab7b1e96006d8074ce2ccf3efa5-run-37748927103-1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 150m
              memory: 128Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 20
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: temporary-files
          emptyDir:
            sizeLimit: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: status-frontend
  namespace: status-platform
spec:
  type: ClusterIP
  selector:
    app: status-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
